App\Entity\Location:
  properties:
    longitude:
      - Range:
          min: -180
          max: 180
          groups: ["edit", "new"]
    latitude:
      - Range:
          min: -90
          max: 90
          groups: ["edit", "new"]